AllCops:
  Exclude:
    - 'Gemfile'
    - 'appops/*'
    - 'appops/**/*'
    - 'bin/**/*'
    - 'Rakefile'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'config/puma.rb'
    - 'config/initializers/secret_token.rb'
    - 'config/initializers/permissions_policy.rb'
    - 'config/initializers/cookies_serializer.rb'
    - 'config/initializers/filter_parameter_logging.rb'
    - 'config/initializers/wrap_parameters.rb'
    - 'config/initializers/content_security_policy.rb'
    - 'db/**/*'
    - 'config/environment.rb'
    - 'config/environments/development.rb'
    - 'config/environments/**/*'
    - 'config/initializers/inflections.rb'
    - 'config/initializers/assets.rb'
    - 'config/initializers/devise.rb'
